// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGz6H-abkIuw71ETZXgTkX4-fzbIfOKEs',
    appId: '1:1004712424270:web:9ba79379b7348fa11ee41f',
    messagingSenderId: '1004712424270',
    projectId: 'eventra-77057',
    authDomain: 'eventra-77057.firebaseapp.com',
    storageBucket: 'eventra-77057.firebasestorage.app',
    measurementId: 'G-FSK8E7G49E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTn-88S4oTMz1eKxdQlBD_not4KATTb6g',
    appId: '1:1004712424270:android:5b7b8de17a6cd71f1ee41f',
    messagingSenderId: '1004712424270',
    projectId: 'eventra-77057',
    storageBucket: 'eventra-77057.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5HaH27AGDL7a_S5cCvVkWJLPDCWE9UmM',
    appId: '1:1004712424270:ios:34119281624fbdae1ee41f',
    messagingSenderId: '1004712424270',
    projectId: 'eventra-77057',
    storageBucket: 'eventra-77057.firebasestorage.app',
    iosBundleId: 'com.example.projectflutteradmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5HaH27AGDL7a_S5cCvVkWJLPDCWE9UmM',
    appId: '1:1004712424270:ios:34119281624fbdae1ee41f',
    messagingSenderId: '1004712424270',
    projectId: 'eventra-77057',
    storageBucket: 'eventra-77057.firebasestorage.app',
    iosBundleId: 'com.example.projectflutteradmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGz6H-abkIuw71ETZXgTkX4-fzbIfOKEs',
    appId: '1:1004712424270:web:981900e2c63034a81ee41f',
    messagingSenderId: '1004712424270',
    projectId: 'eventra-77057',
    authDomain: 'eventra-77057.firebaseapp.com',
    storageBucket: 'eventra-77057.firebasestorage.app',
    measurementId: 'G-LXY1VY2308',
  );
}
